### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by greg88rx** [Vaida12345/PianoTranscription#2]
I love this! It would be great if we could set the output folder as a specific folder or same as source file.

**Comment by Vaida12345** [comment]
Please use the [App Store Version](https://apps.apple.com/au/app/piano-transcriptionist/id6456886504).

**Comment by greg88rx** [comment]
I've started using a new computer and installed the app store version for
the first time.  The results are a little different from what I'm used to.
It is adding some sustain pedal, but I'm seeing a SIGNIFICANTLY greater use
of held notes instead of sustain pedal. The version I was using must have
been an earlier version.  I see there are now tools in the app for tweaking
thresholds.

I love this utility, but I'm a little sad/frustrated since the previous
version was SO SO good.  Can you give me any guidance.

Now using MacOS Sonoma and it won't let me install the version I was
using on my old iMac.

Thanks in advance for any assistance you can provide.
Greg Lile

**Comment by Vaida12345** [comment]
Hmm That is odd. The result from App Store version should be the same as the ones from old versions, as the model used were directly translated. Try adjusting the thresholds a bit? The default parameters were the same as the old ones. Try decreasing the `notes frame` a bit maybe?
Thank you for loving this app!

For the old versions, I can't even open it myself lol. Could you provide me with the version number of the app you installed for your old iMac? Maybe we can find out the parameters used for that version.

**Comment by Vaida12345** [comment]
One way to use the old version is by calling the executable itself. The old application was simply a GUI. The executable can be found at `PianoTranscription.app/Contents/Resources/PianoTranscription/PianoTranscription`. You can call it using `PianoTranscription --audio_path audio.m4a --output_midi_path ~/Desktop/file.midi --checkpoint_path PianoTranscription.app/Contents/Resources/checkpoint.pth `.

I can see the difference in pedal positions, but not the notes.
<img width="400" alt="Screenshot 2023-12-05 at 11 42 33 AM" src="https://github.com/Vaida12345/PianoTranscription/assets/91354917/79256bea-0baa-41c1-8b94-2c95c2323ed4">

I will have a look at it.

**Comment by greg88rx** [comment]
The version I was using was from github PianoTranscription.app.7z dated Dec
20, 2022.  On my old computer the app says version 2.1 (32)

I've rendered both of these MIDIs from the same source file.  One made with
the older version of Piano Transcription on my old computer and the other
one with the app store version.  In the older version file, if you look at
the pedals, you can see the pedal is held down throughout each phrase.  The
newer version seems to identify when the pedal should be held, but doesn't
hold it through the musical phrase in the same way.

I hope this makes sense and that you might have an idea.
Thank you for the speedy response as well.

-Greg

**Comment by Vaida12345** [comment]
Sorry, but I cannot see the screenshot at all. Could you send it again please? Maybe via GitHub?

**Comment by Vaida12345** [comment]
Sorry, did you have a screenshot attached? I cannot see the picture. It would be of great help if you can send me the screenshot. Thank you

**Comment by Vaida12345** [comment]
Hey! I have been checking my code, and there was something wrong with generating the pedals! It has now been fixed, I will release the new version soon. Thank you for pointing it out to me!

**Comment by greg88rx** [comment]
That's great to hear!  Thank you.

**Comment by greg88rx** [comment]
I agree that maybe the notes are unchanged, but here you can see
screenshots of how the pedal is not held through the phrase in the first
screen shot from the current version where the pedal is held in the old
version.  I hope that helps somehow.
[image: Screenshot 2023-12-04 at 11.06.51 PM.png]
[image: Screenshot 2023-12-04 at 11.06.13 PM.png]

**Comment by Vaida12345** [comment]
Sorry, but I cannot see the screenshots

**Comment by greg88rx** [comment]
JPG maybe is better?

[image: Screenshot 2023-12-04 at 11.06.13 PM.jpg][image: Screenshot
2023-12-04 at 11.06.51 PM.jpg]

**Comment by Vaida12345** [comment]
Could you reply on Github please? I cannot see the images at all.

**Comment by greg88rx** [comment]
<img width="1890" alt="Screenshot 2023-12-04 at 11 06 13 PM" src="https://github.com/Vaida12345/PianoTranscription/assets/116593228/38752ee9-f5eb-4af2-ba0c-e976cd55b8cf">
![Screenshot 2023-12-04 at 11 06 51 PM](https://github.com/Vaida12345/PianoTranscription/assets/116593228/8875aeac-7df0-4807-9813-7dcbd59c032c)

**Comment by greg88rx** [comment]
![Screenshot 2023-12-04 at 11 06 51 PM](https://github.com/Vaida12345/PianoTranscription/assets/116593228/821f0135-56d6-4b49-9d0e-a1bf473f8865)

**Comment by Vaida12345** [comment]
Thank you. I can see the screenshots now. Thank you for pointing out this issue to me. This issue has now been fixed.

**Comment by Vaida12345** [comment]
Please wait for the release of the new version on the App Store.

**Comment by Vaida12345** [comment]
The new version has been released on the App Store. Please have a look

**Comment by greg88rx** [comment]
Thank you so much!  It's working just like before.
